package war.vaadin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ProposalDesign extends AbsoluteLayout {
	protected Label imagelabel;
	protected Label tom;
	protected Label refinancelabel;
	protected Label instruction;
	protected Label insset;
	protected Label goal;
	protected Label goaltext;
	protected Label orgdesired;
	protected Label desiredtext;
	protected GridLayout gridlay;
	protected FormLayout formlay1;
	protected TextField property;
	protected TextField downpayment;
	protected TextField mortgageamount;
	protected TextField insuranceAmount;
	protected TextField mortgageins;
	protected TextField lender;
	protected TextField amortization;
	protected TextField mortgageType;
	protected TextField mortgageTerm;
	protected TextField monthlyPaument;
	protected TextField interestRate;
	protected TextField initialvalue;
	protected Label helpinng;
	protected Label helpingtext;
	protected Label recommendation;
	protected GridLayout grid3;
	protected FormLayout form3;
	protected TextField property3;
	protected TextField downpayment3;
	protected GridLayout mortagaamount3;
	protected FormLayout form4;
	protected TextField mortgageAmount3;
	protected TextField amortization4;
	protected TextField mortgagetype4;
	protected TextField mortgageTerm4;
	protected TextField paymentamount4;
	protected TextField interestRate4;
	protected FormLayout formright;
	protected TextField mortgageamount5;
	protected TextField amortization5;
	protected TextField mortgagetype5;
	protected TextField mortgageterm5;
	protected TextField paymentamount5;
	protected TextField interest5;
	protected FormLayout formbottom;
	protected TextField totalMortgageAmount;
	protected TextField totalPayment;
	protected TextField initialhere;
	protected Label consideration;
	protected Label considertext;
	protected Label asyou;
	protected Label lab1;
	protected Label dat;
	protected Table table45;
	protected Label bestfixed;
	protected TextArea textarea;
	protected Label table123;

	public ProposalDesign() {
		Design.read(this);
	}
}
